from __future__ import annotations

from glasswall.models import RemediationPlan, RemediationRun, ScanResult

COMMENT_MARKER = "<!-- glasswall:patch-gap:v1 -->"
REMEDIATION_PR_MARKER = "<!-- glasswall:remediation-pr:v1 -->"


def render_pull_request_comment(scan: ScanResult, plan: RemediationPlan) -> str:
    lines = [
        COMMENT_MARKER,
        "## Glasswall Patch-Gap Report",
        "",
        f"- Findings: `{scan.finding_count}`",
        f"- Top urgency: `{scan.top_urgency_label or 'none'}`",
        f"- Recommendations: `{plan.recommendation_count}`",
    ]
    if scan.policy_path:
        lines.append(f"- Policy: `{scan.policy_path}`")

    if plan.recommendations:
        lines.extend(["", "### Recommended upgrades"])
        for recommendation in plan.recommendations[:8]:
            lines.append(
                f"- `{recommendation.urgency_label}` `{recommendation.name}` "
                f"`{recommendation.current_version} -> {recommendation.target_version or 'manual'}` "
                f"via `{recommendation.source_file}`"
            )
            if recommendation.rationale:
                lines.append(f"  {recommendation.rationale[0]}")
    else:
        lines.extend(["", "No actionable upgrades met the active Glasswall policy."])

    if scan.findings:
        lines.extend(["", "### Top findings"])
        for finding in scan.findings[:5]:
            lines.append(
                f"- `{finding.urgency_label}` `{finding.dependency.name}@{finding.dependency.version}` "
                f"`{finding.vulnerability.canonical_id}` score={finding.urgency_score}"
            )

    lines.extend(
        [
            "",
            "_Generated by Glasswall. This comment is updated in place on new webhook runs._",
        ]
    )
    return "\n".join(lines)


def render_remediation_pull_request(scan: ScanResult, plan: RemediationPlan, remediation: RemediationRun) -> str:
    lines = [
        REMEDIATION_PR_MARKER,
        "## Glasswall Remediation Pull Request",
        "",
        "This PR was opened automatically because Glasswall found supported patch-gap upgrades that can be applied safely now.",
        "",
        f"- Findings in scan: `{scan.finding_count}`",
        f"- Recommendations in plan: `{plan.recommendation_count}`",
        f"- Applied recommendations: `{remediation.applied_recommendation_count}`",
        f"- Changed files: `{remediation.changed_file_count}`",
    ]
    if remediation.changed_files:
        lines.extend(["", "### Files updated"])
        for change in remediation.changed_files:
            packages = ", ".join(change.package_names)
            lines.append(f"- `{change.source_file}` packages=`{packages}` action=`{change.action}`")
    if remediation.skipped:
        lines.extend(["", "### Still needs manual follow-up"])
        for skip in remediation.skipped[:8]:
            lines.append(
                f"- `{skip.urgency_label}` `{skip.name}` via `{skip.source_file}`: {skip.reason}"
            )
    if plan.recommendations:
        lines.extend(["", "### Highest priority recommendation in this run"])
        top = plan.recommendations[0]
        lines.append(
            f"- `{top.name}` `{top.current_version} -> {top.target_version or 'manual'}` "
            f"`{top.urgency_label}` action=`{top.action}`"
        )

    lines.extend(
        [
            "",
            "_Generated by Glasswall auto-remediation. The branch and PR body are updated in place on new runs._",
        ]
    )
    return "\n".join(lines)
