from __future__ import annotations

from glasswall.models import RemediationPlan, ScanResult

COMMENT_MARKER = "<!-- glasswall:patch-gap:v1 -->"


def render_pull_request_comment(scan: ScanResult, plan: RemediationPlan) -> str:
    lines = [
        COMMENT_MARKER,
        "## Glasswall Patch-Gap Report",
        "",
        f"- Findings: `{scan.finding_count}`",
        f"- Top urgency: `{scan.top_urgency_label or 'none'}`",
        f"- Recommendations: `{plan.recommendation_count}`",
    ]
    if scan.policy_path:
        lines.append(f"- Policy: `{scan.policy_path}`")

    if plan.recommendations:
        lines.extend(["", "### Recommended upgrades"])
        for recommendation in plan.recommendations[:8]:
            lines.append(
                f"- `{recommendation.urgency_label}` `{recommendation.name}` "
                f"`{recommendation.current_version} -> {recommendation.target_version or 'manual'}` "
                f"via `{recommendation.source_file}`"
            )
            if recommendation.rationale:
                lines.append(f"  {recommendation.rationale[0]}")
    else:
        lines.extend(["", "No actionable upgrades met the active Glasswall policy."])

    if scan.findings:
        lines.extend(["", "### Top findings"])
        for finding in scan.findings[:5]:
            lines.append(
                f"- `{finding.urgency_label}` `{finding.dependency.name}@{finding.dependency.version}` "
                f"`{finding.vulnerability.canonical_id}` score={finding.urgency_score}"
            )

    lines.extend(
        [
            "",
            "_Generated by Glasswall. This comment is updated in place on new webhook runs._",
        ]
    )
    return "\n".join(lines)

